### ISSUE TITLE
Image display on learn.cs260.click/page/javascript/dom/dom_md

### ISSUE THREAD

**Issue by colbycade** [webprogramming260/.github#153]
The html `<img src="dom.jpg"/>` doesn't display on the website (it shows up as a `<p>` element when I use the debugger) but it does display on the [Github file preview] (https://github.com/webprogramming260/.github/blob/main/profile/javascript/dom/dom.md). When I looked at others that display correctly, it looks like you normal markdown syntax was used: `![DOM](dom.png)` and it generates the correct html using the raw link from Github instead: `<img src="https://raw.githubusercontent.com/webprogramming260/.github/main/profile/javascript/dom/dom.jpg"/>`
This is just a guess for the fix, but it definitely isn't displaying correctly on the website.

**Comment by leesjensen** [comment]
Thanks!
