### ISSUE TITLE
Make WebSocket instruction consistent

### ISSUE THREAD

**Issue by leesjensen** [webprogramming260/.github#181]
The WebSocket instruction uses three slightly different ways for creating a connection.

1. The internal websocket server
2. An explicit Express server that handles the upgrade, but has a hard coded URL
3. A URL that is derived from the existing HTTP URL

Make it so they all use the same example

**Comment by venturadan** [comment]
I think this is done now.  There is actually a fourth place where this applies as well (the debugging page).  I updated both the simple intro and the debugging pages to use the derived-from-HTTP approach that is used by both Chat and Simon.
